create getLogs wrapper
owlprotocol/workspace-public pull request #113
Opened 2024-12-03 03:49 UTC by tota79

2024-12-03 04:03 UTC, leovigna commented
Discussed a bit with @OscBacon 
In the indexer actions for ERC20/721/1155  it better to:
- Not define fromBlock / toBlock
- Use latest block height as toBlock and fromBlock as that number minus 10k

2024-12-03 05:04 UTC, leovigna commented on packages/backend-indexer/src/actions/indexer/getLogs.ts
> +    const toBlock = params.toBlock ?? BigInt(await client.request({ method: "eth_blockNumber" }));
Update to using getBlockNumber action from viem

2024-12-03 05:05 UTC, leovigna commented on packages/backend-indexer/src/actions/indexer/getLogs.ts
> +    let fromBlock = params.fromBlock ?? (typeof toBlock === "bigint" ? toBlock - 10_000n : 0n);
Default value for fromBlock should be undefined no?

2024-12-03 05:07 UTC, leovigna approved these changes
lgtm

2024-12-06 15:20 UTC, OscBacon requested changes

2024-12-06 15:20 UTC, OscBacon commented on packages/backend-indexer/src/actions/indexer/erc1155.ts
> +    // const getLogsAction = getAction(client, getLogs, "getLogs");
remove commented out code

2024-12-06 15:20 UTC, OscBacon commented on packages/backend-indexer/src/actions/indexer/erc20.ts
> +    // const getLogsAction = getAction(client, getLogs, "getLogs");
remove commented out code

2024-12-06 15:20 UTC, OscBacon commented on packages/backend-indexer/src/actions/indexer/erc721.ts
> +    // const getLogsAction = getAction(client, getLogs, "getLogs");
remove commented out code

2024-12-06 15:20 UTC, OscBacon commented on packages/backend-indexer/src/actions/indexer/getLogs.ts
> +        throw new Error("Block range too large. Ensure `toBlock - fromBlock < 10,000`.");
-> "Block range must be less than 10,000 blocks"

2024-12-06 16:10 UTC, OscBacon requested changes

2024-12-06 16:10 UTC, OscBacon commented on packages/backend-indexer/src/actions/indexer/getLogs.ts
> +    const toBlock = params.toBlock ?? (await getBlockNumber(client));
Default for toBlock is latest. Shouldn't you get the block number if `toBlock` is `latest` for consistency?

2024-12-09 10:09 UTC, leovigna commented on packages/backend-indexer/src/actions/indexer/getLogs.ts
> +    const toBlock = params.toBlock ?? (await getBlockNumber(client));
Fair point

2024-12-09 11:03 UTC, OscBacon requested changes

2024-12-09 11:03 UTC, OscBacon commented on packages/backend-indexer/src/actions/indexer/getLogs.ts
> +    let resolvedToBlock: BlockNumber | BlockTag | undefined;
When is resolvedToBlock undefined?

2024-12-09 11:07 UTC, OscBacon approved these changes

2024-12-09 12:22 UTC, merged